#!/usr/bin/env python
#
#  Purpose:
#
# -------------------------------------------------------------------------------

"""
  Skeleton Python module

  ...
"""

import sys

__version__ = "0.0.1"
__id__ = ""


def do_it():
    pass


if __name__ == '__main__' or __name__ == sys.argv[0]:
    do_it()
